class OrderType:
    CALL='CALL'
    PUT='PUT'
    BUY='BUY'
    SELL='SELL'
class AlertType:
    RSI_OVERBOUGHT = "RSI_OVERBOUGHT"
    RSI_OVERSOLD = "RSI_OVERSOLD"
    MACD_SIGNAL_CROSS_MACD ='MACD_SIGNAL_CROSS_MACD'
    MACD_MACD_CROSS_SIGNAL = 'MACD_MACD_CROSS_SIGNAL'
    SMA_CONFIRMATION_UPWARD = 'SMA_CONFIRMATION_UPWARD'
    SMA_CONFIRMATION_DOWNWARD = 'SMA_CONFIRMATION_DOWNWARD'
    DMIPLUS_CROSSOVER_DMINEG= 'DMIPLUS_CROSSOVER_DMINEG'
    DMINEG_CROSSOVER_DMIPLUS = 'DMINEG_CROSSOVER_DMIPLUS'
    ADX_THRESHOLD_UPWARD = 'ADX_THRESHOLD_UPWARD'
    GOLDEN_CROSS_APPEARED = 'GOLDEN_CROSS_APPEARED'
    DEATH_CROSS_APPEARED = 'DEATH_CROSS_APPEARED'
    WITHIN_SR_BAND = 'WITHIN_SR_BAND'
    OUTSIDE_SR_BAND = 'OUTSIDE_SR_BAND'
    # ABOVE_UPPER_SR_BAND = 'ABOVE_UPPER_SR_BAND'
    # BELOW_LOWER_SR_BAND = 'BELOW_LOWER_SR_BAND'
class PositionType:
    LONG = "LONG"
    SHORT = "SHORT"
    SHORT_OPTION = "PUT"
    LONG_OPTION = "CALL"

class PriceGoalChangeType:
    ASSET_SET_PRICE = 'ASSET_SET_PRICE'
    ASSET_POINTS = 'ASSET_POINTS'
    ASSET_PERCENTAGE = 'ASSET_PERCENTAGE'
    OPTION_TICK = 'OPTION_TICK'
    OPTION_PERCENTAGE = 'OPTION_PERCENTAGE'
    OPTION_SET_PRICE = 'OPTION_SET_PRICE'


