class OrderType:
    CALL='CALL'
    PUT='PUT'
    BUY='BUY'
    SELL='SELL'
class AlertType:
    RSI_OVERBOUGHT = "RSI_OVERBOUGHT"
    RSI_OVERSOLD = "RSI_OVERSOLD"
    MACD_SIGNAL_CROSS_MACD ='MACD_SIGNAL_CROSS_MACD'
    MACD_MACD_CROSS_SIGNAL = 'MACD_MACD_CROSS_SIGNAL'
    SMA_CROSSOVER_UPWARD = 'SMA_CROSSOVER_UPWARD'
    SMA_CROSSOVER_DOWNWARD = 'SMA_CROSSOVER_DOWNWARD'
    DMIPLUS_CROSSOVER_DMINEG= 'DMIPLUS_CROSSOVER_DMINEG'
    DMINEG_CROSSOVER_DMIPLUS = 'DMINEG_CROSSOVER_DMIPLUS'
    ADX_OVERTHRESHOLD_UPWARD = 'ADX_OVERTHRESHOLD_UPWARD'
class PositionType:
    LONG = "LONG"
    SHORT = "SHORT"
